<#  Publish-KnowledgeWiki.ps1 — publish the project knowledge registry to the repo's GitHub Wiki.

    Generates one Home page (index by domain) plus one page per domain from
    knowledge/registry.json, then clones <repo>.wiki.git, writes the pages, and pushes.
    This is the Phase-2 layer that anchors knowledge-ops to GitHub (GitOps for knowledge).

    Testable page generation is exposed via -PagesOnly -OutDir (pure, no git/network).
    The clone -> commit -> push path mirrors New-BoardPR: the token travels ONLY as an env
    var read by a one-shot credential helper, never on the command line or in the remote. #>
[CmdletBinding()]
param(
    [string]$Root = (Get-Location).Path,
    [string]$Repo,                       # owner/name; default derived from origin
    [string]$TokenVar = '',              # default resolved from the owner (New-BoardPR map)
    [string]$Date = (Get-Date -Format 'yyyy-MM-dd'),
    [switch]$PagesOnly,                  # generate pages into -OutDir and stop (no git) — for tests/preview
    [string]$OutDir,                     # required with -PagesOnly
    [switch]$DryRun,                     # resolve + generate, but do not push
    [switch]$Json
)
$ErrorActionPreference = 'Stop'

function Format-Ref  { param([string]$s) if ($s -match '^(https?)://') { "[$s]($s)" } else { "``$s``" } }
function Format-Cell { param([string]$s) ([string]$s -replace '\|','\|') }
# Wiki page filename (and link target) for a domain — spaces/odd chars -> hyphens.
function Get-DomainSlug { param([string]$d) 'Knowledge-' + (($d -replace '[^\w-]+','-') -replace '-+','-').Trim('-') }

# -- Read the registry --------------------------------------------------------------
. (Join-Path $PSScriptRoot 'KnowledgeRegistryIo.ps1')
$regPath = Resolve-KnowledgeRegistryPath -Root $Root
if (-not (Test-Path -LiteralPath $regPath)) { throw "No registry at $regPath — run /knowledge add first." }
$reg  = Read-KnowledgeRegistry -Path $regPath
$refs = @($reg.references)
$project = if ($reg.project) { $reg.project } else { Split-Path $Root -Leaf }
$domains = @($refs | Select-Object -ExpandProperty domain -Unique | Sort-Object)

# -- Build the pages in memory (name -> markdown) -----------------------------------
$pages = [ordered]@{}

$homeSb = [Text.StringBuilder]::new()
[void]$homeSb.AppendLine("<!-- GENERATED by /knowledge wiki — do not edit here; edit knowledge/registry.json in the repo. -->")
[void]$homeSb.AppendLine("# Knowledge — $project")
[void]$homeSb.AppendLine("")
[void]$homeSb.AppendLine("Catalog of external references by domain. Source of truth: ``knowledge/registry.json`` in the repo.")
[void]$homeSb.AppendLine("")
if ($refs.Count -eq 0) {
    [void]$homeSb.AppendLine("_No references yet. Add one with ``/knowledge add``._")
} else {
    [void]$homeSb.AppendLine("| Domain | References |")
    [void]$homeSb.AppendLine("|--------|-----------|")
    foreach ($domain in $domains) {
        $count = @($refs | Where-Object domain -eq $domain).Count
        [void]$homeSb.AppendLine(("| [{0}]({1}) | {2} |" -f (Format-Cell $domain), (Get-DomainSlug $domain), $count))
    }
    [void]$homeSb.AppendLine("")
    [void]$homeSb.AppendLine("_$($refs.Count) reference(s) across $($domains.Count) domain(s). Last published $Date._")

    foreach ($domain in $domains) {
        $p = [Text.StringBuilder]::new()
        [void]$p.AppendLine("<!-- GENERATED by /knowledge wiki — do not edit here; edit knowledge/registry.json in the repo. -->")
        [void]$p.AppendLine("# $domain")
        [void]$p.AppendLine("")
        [void]$p.AppendLine("| Title | Type | Ref | Note |")
        [void]$p.AppendLine("|-------|------|-----|------|")
        foreach ($r in ($refs | Where-Object domain -eq $domain | Sort-Object title)) {
            [void]$p.AppendLine(("| {0} | {1} | {2} | {3} |" -f (Format-Cell $r.title), $r.type, (Format-Ref $r.ref), (Format-Cell $r.note)))
        }
        [void]$p.AppendLine("")
        [void]$p.AppendLine("[← Home](Home)")
        $pages[(Get-DomainSlug $domain)] = $p.ToString()
    }
}
$pages['Home'] = $homeSb.ToString()

# -- -PagesOnly: write pages to OutDir and stop (testable, no git) -------------------
if ($PagesOnly) {
    if (-not $OutDir) { throw "-PagesOnly requires -OutDir." }
    New-Item -ItemType Directory -Path $OutDir -Force | Out-Null
    $written = foreach ($name in $pages.Keys) {
        $fp = Join-Path $OutDir "$name.md"
        $pages[$name] | Set-Content -LiteralPath $fp -Encoding utf8
        $fp
    }
    if ($Json) { [pscustomobject]@{ pages = @($pages.Keys); files = @($written) } | ConvertTo-Json -Depth 6 } else { @($written) }
    return
}

# -- Resolve repo + account (mirror New-BoardPR) ------------------------------------
if (-not $Repo) {
    $url = git remote get-url origin 2>$null
    if (-not $url) { throw "No origin remote here — pass -Repo owner/name." }
    if     ($url -match '(?i)^https://(?:[^@/]+@)?github\.com/([^/]+)/([^/]+?)(?:\.git)?/?$') { $Repo = "$($Matches[1])/$($Matches[2])" }
    elseif ($url -match '(?i)^git@github\.com:([^/]+)/([^/]+?)(?:\.git)?$')                   { $Repo = "$($Matches[1])/$($Matches[2])" }
    else { throw "Could not derive owner/name from '$url' — pass -Repo owner/name." }
}
if ($Repo -notmatch '^[^/]+/[^/]+$') { throw "-Repo must be owner/name (got '$Repo')." }
$owner = ($Repo -split '/')[0]
$ownerVarMap = @{ 'CSalcedoDataBI' = 'GITHUB_TOKEN_PERSONAL'; 'PAL-Devs' = 'GITHUB_TOKEN_BUSINESS' }
if (-not $TokenVar) {
    if ($ownerVarMap.ContainsKey($owner)) { $TokenVar = $ownerVarMap[$owner] }
    else { $TokenVar = 'GITHUB_TOKEN_PERSONAL'; Write-Host "AVISO: owner '$owner' sin mapear — uso la personal (-TokenVar para forzar)." -ForegroundColor Yellow }
}
$token = [System.Environment]::GetEnvironmentVariable($TokenVar, 'User')
if ([string]::IsNullOrWhiteSpace($token)) { throw "$TokenVar no esta en el entorno USER de Windows." }
$env:GH_TOKEN = $token

# Confirm identity + that the wiki is enabled on the repo.
$login = "$(gh api user --jq .login 2>$null)".Trim()
if ($LASTEXITCODE -ne 0 -or -not $login) { throw "El token de $TokenVar no autentica contra la API." }
$repoInfo = gh api "repos/$Repo" 2>$null | ConvertFrom-Json
if (-not $repoInfo) { throw "'$login' no ve el repo $Repo (no existe o sin acceso). Cuenta equivocada?" }
if (-not $repoInfo.permissions.push) { throw "'$login' NO tiene permiso de push en $Repo." }
if (-not $repoInfo.has_wiki) { throw "El Wiki esta deshabilitado en $Repo. Actívalo en Settings -> Features -> Wikis y reintenta." }

$wikiUrl = "https://github.com/$Repo.wiki.git"
Write-Host "=== knowledge-wiki  $Repo ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Identidad : $login  (via $TokenVar)"
Write-Host "  Registry  : $($refs.Count) referencia(s), $($domains.Count) dominio(s)"
Write-Host "  Paginas   : $($pages.Count) ($($pages.Keys -join ', '))"
Write-Host "  Wiki      : $wikiUrl"
Write-Host ""

if ($DryRun) {
    Write-Host "DRY-RUN: no se clona ni se empuja nada." -ForegroundColor Yellow
    if ($Json) { [pscustomobject]@{ repo=$Repo; pages=@($pages.Keys); wikiUrl=$wikiUrl; dryRun=$true } | ConvertTo-Json -Depth 6 }
    return
}

# -- Clone the wiki, write pages, commit, push ----------------------------------------
$tmp = Join-Path ([IO.Path]::GetTempPath()) ("knwiki-" + [guid]::NewGuid().ToString('N'))
$helper = 'credential.helper=!f(){ echo username=x-access-token; echo password=$ABIOS_WIKI_TOKEN; };f'
$env:ABIOS_WIKI_TOKEN = $token
try {
    git -c credential.helper= -c $helper clone --quiet $wikiUrl $tmp 2>$null
    if ($LASTEXITCODE -ne 0) {
        # GitHub creates the wiki git repo lazily — it does not exist until the first page
        # is saved through the web UI. There is no REST endpoint to bootstrap it.
        throw @"
ERROR: El repositorio wiki de $Repo aun no esta inicializado.

GitHub crea el wiki git repo de forma lazy: no existe hasta que se guarda
la primera pagina desde la interfaz web. No hay endpoint REST para crearlo.

Para inicializarlo:
  1. Abre https://github.com/$Repo/wiki en el navegador
  2. Haz clic en "Create the first page"
  3. Escribe cualquier contenido y pulsa "Save Page"
  4. Vuelve a ejecutar este comando

"@
    }
    foreach ($name in $pages.Keys) {
        $pages[$name] | Set-Content -LiteralPath (Join-Path $tmp "$name.md") -Encoding utf8
    }
    git -C $tmp add -A
    $status = git -C $tmp status --porcelain
    if (-not $status) {
        Write-Host "OK  Wiki ya estaba al dia (sin cambios)." -ForegroundColor Green
    } else {
        git -C $tmp -c user.name='agentic-board' -c user.email='noreply@agentic-board' `
            commit --quiet -m "knowledge: publish registry ($($refs.Count) refs, $Date)"
        if ($LASTEXITCODE -ne 0) { throw "git commit fallo (exit $LASTEXITCODE)." }
        git -c credential.helper= -c $helper -C $tmp push --quiet origin HEAD:master
        if ($LASTEXITCODE -ne 0) { throw "git push al wiki fallo (exit $LASTEXITCODE)." }
        Write-Host "OK  Wiki publicado ($($pages.Count) paginas)." -ForegroundColor Green
    }
} finally {
    Remove-Item Env:ABIOS_WIKI_TOKEN -ErrorAction SilentlyContinue
    Remove-Item -LiteralPath $tmp -Recurse -Force -ErrorAction SilentlyContinue
}

$viewUrl = "https://github.com/$Repo/wiki"
Write-Host "  Ver: $viewUrl"
if ($Json) { [pscustomobject]@{ repo=$Repo; pages=@($pages.Keys); wikiUrl=$wikiUrl; viewUrl=$viewUrl } | ConvertTo-Json -Depth 6 }
