#Requires -Modules Pester
<#  Pester tests for Publish-KnowledgeWiki.ps1 page generation (-PagesOnly, no git/network).
    Builds a two-domain registry, generates the wiki pages, and asserts the Home index,
    the per-domain pages, slug/link forms, and the empty-registry path. #>
BeforeAll {
    $script:Engine = Join-Path $PSScriptRoot '..' 'scripts' 'Publish-KnowledgeWiki.ps1' | Resolve-Path
    function New-Root { Join-Path ([IO.Path]::GetTempPath()) ("knwiki-t-" + [guid]::NewGuid().ToString('N')) }
    function Seed-Registry {
        param($root, $refs)
        New-Item -ItemType Directory -Path (Join-Path $root 'knowledge') -Force | Out-Null
        ([pscustomobject]@{ version=1; project='fix'; domains=@('Fabric','Power-Query'); references=$refs }) |
            ConvertTo-Json -Depth 8 | Set-Content -LiteralPath (Join-Path $root 'knowledge' 'registry.json') -Encoding utf8
    }
}

Describe 'Publish-KnowledgeWiki (page generation)' {
    BeforeAll {
        $script:Root = New-Root
        Seed-Registry $script:Root @(
            [pscustomobject]@{ id='kn_001'; domain='Fabric';      type='url'; title='Cap API'; ref='https://learn.microsoft.com/x'; note='trial->prod'; added='2026-07-07' }
            [pscustomobject]@{ id='kn_002'; domain='Power-Query'; type='md';  title='PQ Notes'; ref='docs/pq.md';                    note='mine';        added='2026-07-07' }
        )
        $script:Out = Join-Path $script:Root 'out'
        & $script:Engine -Root $script:Root -OutDir $script:Out -PagesOnly -Date '2026-07-08' | Out-Null
        $script:HomePage = Get-Content -LiteralPath (Join-Path $script:Out 'Home.md') -Raw
        $script:Fab      = Get-Content -LiteralPath (Join-Path $script:Out 'Knowledge-Fabric.md') -Raw
    }
    AfterAll { if ($script:Root -and (Test-Path $script:Root)) { Remove-Item $script:Root -Recurse -Force } }

    It 'writes a Home page plus one page per domain' {
        (Get-ChildItem -LiteralPath $script:Out -Filter *.md | Select-Object -ExpandProperty Name | Sort-Object) |
            Should -Be @('Home.md','Knowledge-Fabric.md','Knowledge-Power-Query.md')
    }
    It 'stamps the do-not-edit generated header' { $script:HomePage | Should -Match 'GENERATED by /knowledge wiki' }
    It 'links Home to each domain page by slug' {
        $script:HomePage | Should -Match '\[Fabric\]\(Knowledge-Fabric\)'
        $script:HomePage | Should -Match '\[Power-Query\]\(Knowledge-Power-Query\)'
    }
    It 'reports the reference and domain counts on Home' { $script:HomePage | Should -Match '2 reference\(s\) across 2 domain\(s\)' }
    It 'renders urls as links and local refs as code on the domain page' {
        $script:Fab | Should -Match '\[https://learn\.microsoft\.com/x\]\(https://learn\.microsoft\.com/x\)'
        (Get-Content -LiteralPath (Join-Path $script:Out 'Knowledge-Power-Query.md') -Raw) | Should -Match '`docs/pq\.md`'
    }
    It 'back-links each domain page to Home' { $script:Fab | Should -Match '\[← Home\]\(Home\)' }
}

Describe 'Publish-KnowledgeWiki (empty registry)' {
    It 'emits only a Home page inviting the first add' {
        $root = New-Root; Seed-Registry $root @()
        $out = Join-Path $root 'out'
        & $script:Engine -Root $root -OutDir $out -PagesOnly | Out-Null
        (Get-ChildItem -LiteralPath $out -Filter *.md | Select-Object -ExpandProperty Name) | Should -Be 'Home.md'
        (Get-Content -LiteralPath (Join-Path $out 'Home.md') -Raw) | Should -Match 'No references yet'
        Remove-Item $root -Recurse -Force
    }
    It 'throws when there is no registry' {
        $root = New-Root; New-Item -ItemType Directory -Path $root -Force | Out-Null
        { & $script:Engine -Root $root -OutDir (Join-Path $root 'out') -PagesOnly } | Should -Throw
        Remove-Item $root -Recurse -Force
    }
}

Describe 'Publish-KnowledgeWiki (uninitialized wiki error)' {
    BeforeAll {
        $script:UninitRoot = New-Root
        Seed-Registry $script:UninitRoot @(
            [pscustomobject]@{ id='kn_001'; domain='TestDomain'; type='url'; title='Test Ref'; ref='https://example.com'; note='test'; added='2026-07-23' }
        )
        # Save any existing git/gh functions so AfterAll can restore them.
        $script:PriorGit = Get-Item 'Function:git' -ErrorAction SilentlyContinue
        $script:PriorGh  = Get-Item 'Function:gh'  -ErrorAction SilentlyContinue
        # Override git/gh as PowerShell functions — they shadow the real executables inside PS.
        # git mock: exit 128 when called with 'clone' (mimics an uninitialized wiki repo).
        function global:git {
            if ('clone' -in $args) { $global:LASTEXITCODE = 128; return }
            $global:LASTEXITCODE = 0
        }
        # gh mock: return minimal fake auth data so the auth/wiki-enabled checks pass.
        function global:gh {
            if ($args[0] -eq 'api' -and 'user' -in $args) {
                Write-Output 'test-user'
            } elseif ($args[0] -eq 'api') {
                Write-Output '{"has_wiki":true,"permissions":{"push":true},"name":"test"}'
            }
            $global:LASTEXITCODE = 0
        }
        # Use a test-scoped env-var name so GITHUB_TOKEN_PERSONAL is never touched.
        [System.Environment]::SetEnvironmentVariable('ABIOS_TEST_WIKI_TOKEN', 'fake-unit-test-token', 'User')
    }
    AfterAll {
        [System.Environment]::SetEnvironmentVariable('ABIOS_TEST_WIKI_TOKEN', $null, 'User')
        Remove-Item Env:GH_TOKEN -ErrorAction SilentlyContinue
        Remove-Item 'Function:git' -ErrorAction SilentlyContinue
        Remove-Item 'Function:gh'  -ErrorAction SilentlyContinue
        if ($script:PriorGit) { New-Item -Path 'Function:git' -Value $script:PriorGit.ScriptBlock -Force | Out-Null }
        if ($script:PriorGh)  { New-Item -Path 'Function:gh'  -Value $script:PriorGh.ScriptBlock  -Force | Out-Null }
        if ($script:UninitRoot -and (Test-Path $script:UninitRoot)) { Remove-Item $script:UninitRoot -Recurse -Force }
    }

    It 'throws with the actionable step to create the first wiki page via web UI' {
        { & $script:Engine -Root $script:UninitRoot -Repo 'test-owner/test-wiki-repo' -TokenVar ABIOS_TEST_WIKI_TOKEN } |
            Should -Throw -ExpectedMessage '*Create the first page*'
    }
    It 'error message includes the wiki URL so the user can navigate directly' {
        { & $script:Engine -Root $script:UninitRoot -Repo 'test-owner/test-wiki-repo' -TokenVar ABIOS_TEST_WIKI_TOKEN } |
            Should -Throw -ExpectedMessage '*github.com/test-owner/test-wiki-repo/wiki*'
    }
}
